services:
  mysql:
    image: mysql:8.0
    container_name: mysql_final_project
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
    volumes:
      - mysql_final_project:/var/lib/mysql
    networks:
      - db_network
  
  mongodb:
    image: mongo:8.0.5
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db_final

volumes:
  mysql_final_project:
  dbdata:

networks:
  db_network:
    driver: bridge
