CREATE TABLE patients (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  document_number VARCHAR(15) UNIQUE NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  picture_url VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);